### ISSUE TITLE
Tarefa 9 - Mudar tratativas de inputs errados para Exceptions

### ISSUE THREAD

**Issue by pedromsilvaalves** [pedromsilvaalves/desempenho-esportivo#3]
### Mudar a tratativa de inputs errados nas classes para jogar exceptions no lugar de colocar valores padrões.

Atualmente quando o setter da classe identifica um input errado ele coloca um valor padrão.
Ex. 
```
Classe Jogador
public string nome
        {
            get { return _nome; }
            set
            {
                if (value.Length != 0)
                    _nome = value;
                else
                    _nome = "Joaozin Perna de Pau";
            }
        }
```

O que é necessário fazer é trocar essa tratativa para que em vez de colocar um valor padrão ele jogar um exception de nome inválido.
Ex.
```
Classe Jogador
public string nome
        {
            get { return _nome; }
            set
            {
                if (value.Length != 0)
                    _nome = value;
                else
                    throw new InvalidParameterException();
            }
        }

```

Para realizar isso é preciso criar uma classe de Exception que herda da classe mãe Exception que atenda ao caso.

- Classes a serem adaptadas
- [x] Jogada
- [x] Jogador
- [x] Posicao
- [x] Time

**Comment by fpabdalla** [comment]
Feito. Nas classes Jogada e Jogador alguns get e set foram mantidos. São eles:

Jogada:
- pontosJogada (definido pelo Dictionary)
- multiplicador (definido pelo Dictionary) 

Jogador:
- posicao (o mesmo vem da classe posição e eu não soube como tratar essa exceção).

Fora isso, todos feitos.
